[package]
name = "gdal-win"
version = "3.100.4"
edition = "2021"
description = "GDAL for Rust / Windows"
license = "Apache-2.0"
repository = "https://github.com/geocrate/gdal-win"

[dependencies]
bitflags = "2.8.0"
chrono = "0.4.39"
geo-types = "0.7.15"
tempfile = "3.16.0"
thiserror = "2.0.11"
