[package]
name = "gdal-win"
version = "3.100.0"
edition = "2021"

[dependencies]
bitflags = "2.8.0"
chrono = "0.4.39"
gdal_sys = { path = "./gdal_sys" }
geo-types = "0.7.15"
tempfile = "3.16.0"
thiserror = "2.0.11"
