[package]
name = "gdal-build"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.12", features = ["blocking"] }
sevenz-rust = "0.6.1"

[build-dependencies]
reqwest = { version = "0.12.12", features = ["blocking"] }
sevenz-rust = "0.6.1"